password: ENC[AES256_GCM,data:tHu09AUMEF3ao3X4Lwc=,iv:kyR+twGM6IM6moyoNJOZ4DcQ2efmnpGa5HoNnaZoPSA=,tag:e4NUDO3QEFZsp8KaD8ClBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-14T21:26:51Z"
    mac: ENC[AES256_GCM,data:hCnW9U/E6sQunqaV4FUu+IgKJnlT+DjlcXM1pGqnpbcXwIX7KMSDNvtg26RXKXW0RPj+qnVWdD/jpRCCZUIJRQ5o4FC76jHqJ8h5lc0htuNaevbxkQSr9A1+8kOGAdC9cFa9oSvx/Q3cPlfR14KQS2axxW3/MfZLCX1fe0IGvZQ=,iv:HAzNLgxavY7oDa/8zQ3KvimpG/X8o3s6zKMXaKu9+20=,tag:19RbppFa/0hfSdY4Qbcq6w==,type:str]
    pgp:
        - created_at: "2024-04-14T21:13:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DSuZowMTy8koSAQdAq/1r6H2Vf2NGM9ggQNqhRKz3Pox+Mz7d2mmkehXVbwow
            sUTVVpBz2zXzRMJBoukKwdUPKenYFsU7D9A7CJ7FuOJgyBu7eo8YfG5VowaCVbjX
            1GYBCQIQ9MqaEmLqH6/IlL6aY6FiWTHYsYO5PfQV5kAcp/o+hj7API/BmbQnJ2ec
            zjCnrkHMSudRCVXcfJ5zhzcmczeI/aa6Xjxqf+5bKThgoGcMRvmoXk4xak4PC/VU
            MautpGA0PjA=
            =FjPi
            -----END PGP MESSAGE-----
          fp: 9391F50A08551029AAA391AEC68B6CBA56AB9B98
    unencrypted_suffix: _unencrypted
    version: 3.8.1
