---

- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yaml

- name: Install docker-compose
  ansible.builtin.include_tasks: install_compose.yaml

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker